name: econ
channels:
  - pytorch
  - conda-forge
  - fvcore
  - iopath
  - bottler
  - defaults
dependencies:
  - python=3.8
  - nvidiacub
  - torchvision
  - fvcore
  - iopath
  - pyembree
  - cupy
  - cython
  - pip